USE [BD_API_ECOFUTURO]
GO
/****** Object:  Table [weco].[CLIENTE]    Script Date: 26/10/2020 16:06:22 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [weco].[CLIENTE] (
	[CLIE_CLIENTE_ID_BI] [bigint] IDENTITY(1, 1) NOT NULL
	,[CLIE_CORREO_ELECTRONICO_VC] [varchar](MAX)
    ,[CLIE_CLAVE_VC] [varchar] (MAX)  
	,[CLIE_CI_VC] [varchar](80)
	,[CLIE_CI_EXPEDICION_VC] [varchar](20)
	,[CLIE_NOMBRE_COMPLETO_VC] [varchar](MAX)
	,[CLIE_GENERO_VC] [varchar](80)
	,[CLIE_FECHA_NACIMIENTO_DT] [date]
	,[CLIE_EDAD_IN] [int]
	,[CLIE_DEPARTAMENTO_VC] [varchar](20)
	,[CLIE_CIUDAD_VC] [varchar](MAX)
	,[CLIE_DIRECCION_VC] [varchar](MAX)
	,[CLIE_NUMERO_CELULAR_VC] [varchar](20)
	,[CLIE_NUMERO_FIJO_VC] [varchar](20)
	,[CLIE_NIVEL_EDUCACION_VC] [varchar](100)
	,[CLIE_DISCAPACIDAD_BT] [bit]
	,[CLIE_TIPO_DISCAPACIDAD_VC] [varchar](MAX)
	,[CLIE_NOMBRE_REFERENCIA_VC] [varchar](MAX)
	,[CLIE_CELULAR_REFERENCIA_VC] [varchar](20)
	,[CLIE_TERMINOS_Y_CONDICIONES_ACEPTADOS_BT] [bit]
	,[CLIE_ROL_IN][int]
	,[CLIE_TOKEN_VERIFICACION_EMAIL_VC] [varchar](max)
	,[CLIE_FECHA_VERIFICACION_DT] [datetime]
	,[CLIE_ESTADO_VERIFICACION_BT] [bit]
	,[CLIE_RESTABLECER_TOKEN_VERIFICACION_EMAIL_VC] [varchar](max)
	,[CLIE_FECHA_EXPIRACION_TOKEN_RESTABLECER_DT] [datetime]
	,[CLIE_FECHA_CAMBIO_CONTRASENA_VC] [datetime]
	,[CLIE_REGISTRO_COMPLETO_BT] [bit]
	,[CLIE_USUARIO_CREACION_VC] [varchar](20)
	,[CLIE_FECHA_CREACION_DT] [datetime]
	,[CLIE_USUARIO_MODIFICACION_VC] [varchar](20)
	,[CLIE_FECHA_MODIFICACION_DT] [datetime]
	,[CLIE_ESTADO_BT] [bit]
	,CONSTRAINT [PK_CLIENTE] PRIMARY KEY ([CLIE_CLIENTE_ID_BI])
	)
GO

/****** Object:  Table [weco].[MODULO]    Script Date: 26/10/2020 16:06:22 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [weco].[MODULO] (
	[MODU_MODULO_ID_BI] [bigint] IDENTITY(1, 1) NOT NULL
	,[MODU_NUMERO_MODULO_IN] [int]
	,[MODU_NOMBRE_VC] [varchar](200)
    ,[MODU_DESCRIPCION_VC] [varchar] (MAX)
	,[MODU_USUARIO_CREACION_VC] [varchar](20)
	,[MODU_FECHA_CREACION_DT] [datetime]
	,[MODU_USUARIO_MODIFICACION_VC] [varchar](20)
	,[MODU_FECHA_MODIFICACION_DT] [datetime]
	,[MODU_ESTADO_BT] [bit]
	,CONSTRAINT [PK_MODULO] PRIMARY KEY ([MODU_MODULO_ID_BI])
	)
GO

/****** Object:  Table [weco].[PREGUNTA]    Script Date: 26/10/2020 16:06:22 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [weco].[PREGUNTA] (
	[PREG_PREGUNTA_ID_BI] [bigint] IDENTITY(1, 1) NOT NULL
	,[PREG_PREGUNTA_VC] [varchar](MAX)
	,[PREG_PREGUNTA_DESCRIPCION_VC] [varchar](MAX)
    ,[PREG_MODULO_ID_BI] [bigint] NOT NULL
	,[PREG_TIPO_CAMPO_VC] [varchar] (200)
	,[PREG_USUARIO_CREACION_VC] [varchar](20)
	,[PREG_FECHA_CREACION_DT] [datetime]
	,[PREG_USUARIO_MODIFICACION_VC] [varchar](20)
	,[PREG_FECHA_MODIFICACION_DT] [datetime]
	,[PREG_ESTADO_BT] [bit]
	,CONSTRAINT [PK_PREGUNTA] PRIMARY KEY (PREG_PREGUNTA_ID_BI)
	,CONSTRAINT [FK_PREGUNTA] FOREIGN KEY ([PREG_MODULO_ID_BI]) REFERENCES [weco].[MODULO] (MODU_MODULO_ID_BI) 
	)
CREATE INDEX INDEX_PREGUNTA_MODULO ON [weco].[PREGUNTA]([PREG_MODULO_ID_BI]);
GO

/****** Object:  Table [weco].[RESPUESTA]    Script Date: 26/10/2020 16:06:22 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [weco].[RESPUESTA] (
	[RESP_RESPUESTA_ID_BI] [bigint] IDENTITY(1, 1) NOT NULL
	,[RESP_DETALLE_RESPUESTA_VC] [varchar](MAX)
    ,[RESP_ESTADO_RESPUESTA_CORRECTA_BT] [bit]
	,[RESP_PREGUNTA_ID_BI] [bigint]
	,[RESP_USUARIO_CREACION_VC] [varchar](20)
	,[RESP_FECHA_CREACION_DT] [datetime]
	,[RESP_USUARIO_MODIFICACION_VC] [varchar](20)
	,[RESP_FECHA_MODIFICACION_DT] [datetime]
	,[RESP_ESTADO_BT] [bit]
	,CONSTRAINT [PK_RESPUESTA] PRIMARY KEY (RESP_RESPUESTA_ID_BI)
	,CONSTRAINT [FK_RESPUESTA] FOREIGN KEY ([RESP_PREGUNTA_ID_BI]) REFERENCES [weco].[PREGUNTA] ([PREG_PREGUNTA_ID_BI]) 
	)
CREATE INDEX INDEX_RESPUESTA_PREGUNTA ON [weco].[RESPUESTA]([RESP_PREGUNTA_ID_BI]);
GO

/****** Object:  Table [weco].[RESPUESTA_CLIENTE]    Script Date: 26/10/2020 16:06:22 p.m. ******/
/*SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [weco].[RESPUESTA_CLIENTE] (
	[REUS_RESPUESTA_CLIENTE_ID_BI] [bigint] IDENTITY(1, 1) NOT NULL
	,[REUS_RESPUESTA_ID_BI][bigint] NOT NULL
    ,[REUS_CLIENTE_ID_BI] [bigint] NOT NULL
    ,[REUS_PUNTAJE_OBTENIDO_DC] [decimal](16,2)
	,[REUS_USUARIO_CREACION_VC] [varchar](20)
	,[REUS_FECHA_CREACION_DT] [datetime]
	,[REUS_USUARIO_MODIFICACION_VC] [varchar](20)
	,[REUS_FECHA_MODIFICACION_DT] [datetime]
	,[REUS_ESTADO_BT] [bit]
	,CONSTRAINT [PK_RESPUESTA_CLIENTE] PRIMARY KEY ([REUS_RESPUESTA_CLIENTE_ID_BI])
	,CONSTRAINT [FK_RESPUESTA_CLIENTE_1] FOREIGN KEY ([REUS_RESPUESTA_ID_BI]) REFERENCES [weco].[RESPUESTA] ([RESP_RESPUESTA_ID_BI]) 
	,CONSTRAINT [FK_RESPUESTA_CLIENTE_2] FOREIGN KEY ([REUS_CLIENTE_ID_BI]) REFERENCES [weco].[CLIENTE] ([CLIE_CLIENTE_ID_BI]) 
	);
CREATE INDEX INDEX_RESPUESTA_CLIENTE_1 ON [weco].[RESPUESTA_CLIENTE]([REUS_RESPUESTA_ID_BI]);
CREATE INDEX INDEX_RESPUESTA_CLIENTE_2 ON [weco].[RESPUESTA_CLIENTE]([REUS_CLIENTE_ID_BI]);
GO*/

/****** Object:  Table [weco].[RESPUESTA_CLIENTE]    Script Date: 26/10/2020 16:06:22 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [weco].[CLIENTE_MODULO] (
	[CLMO_CLIENTE_MODULO_ID_BI] [bigint] IDENTITY(1, 1) NOT NULL
	,[CLMO_MODULO_ID_BI][bigint] NOT NULL
    ,[CLMO_CLIENTE_ID_BI] [bigint] NOT NULL
    ,[CLMO_CUPON_VC] [varchar] (max) 
	,[CLMO_USUARIO_CREACION_VC] [varchar](20)
	,[CLMO_FECHA_CREACION_DT] [datetime]
	,[CLMO_USUARIO_MODIFICACION_VC] [varchar](20)
	,[CLMO_FECHA_MODIFICACION_DT] [datetime]
	,[CLMO_ESTADO_BT] [bit]
	,CONSTRAINT [PK_CLIENTE_MODULO] PRIMARY KEY ([CLMO_CLIENTE_MODULO_ID_BI])
	,CONSTRAINT [FK_CLIENTE_MODULO_1] FOREIGN KEY ([CLMO_MODULO_ID_BI]) REFERENCES [weco].[MODULO] ([MODU_MODULO_ID_BI]) 
	,CONSTRAINT [FK_CLIENTE_MODULO_2] FOREIGN KEY ([CLMO_CLIENTE_ID_BI]) REFERENCES [weco].[CLIENTE] ([CLIE_CLIENTE_ID_BI]) 
	);
CREATE INDEX INDEX_CLIENTE_MODULO_1 ON [weco].[CLIENTE_MODULO]([CLMO_MODULO_ID_BI]);
CREATE INDEX INDEX_CLIENTE_MODULO_2 ON [weco].[CLIENTE_MODULO]([CLMO_CLIENTE_ID_BI]);
GO

/****** Object:  Table [weco].[USUARIO_WEP_API]    Script Date: 26/10/2020 16:06:22 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [weco].[USUARIO_WEP_API] (
	[USWA_USUARIO_WEP_API_ID_BI] [bigint] IDENTITY(1, 1) NOT NULL
	,[USWA_USUARIO_NOMBRE_VC][varchar](200) 
    ,[USWA_CONTRASENA_ID_VB] [varbinary] (MAX)
	,[USWA_TOKEN_PUBLICO_UN] [uniqueidentifier]
	,[USWA_ESTADO_VC] [varchar](1)
	,[USWA_USUARIO_CREACION_VC] [varchar](20)
	,[USWA_FECHA_CREACION_DT] [datetime]
	,[USWA_USUARIO_MODIFICACION_VC] [varchar](20)
	,[USWA_FECHA_MODIFICACION_DT] [datetime]
	,[USWA_ESTADO_BT] [bit]
	,CONSTRAINT [PK_USUARIO_WEB_API] PRIMARY KEY ([USWA_USUARIO_WEP_API_ID_BI])
	);
GO

/****** Object:  Table [weco].[POLITICA]    Script Date: 26/10/2020 16:06:22 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [weco].[POLITICA] (
	[POLI_POLITICA_ID_BI] [bigint] IDENTITY(1, 1) NOT NULL
	,[POLI_NOMBRE_VC][varchar](MAX) 
    ,[POLI_DESCRIPCION_VC] [varchar] (MAX)
    ,[POLI_ESTADO_VC] [varchar] (1)
	,[POLI_USUARIO_CREACION_VC] [varchar](20)
	,[POLI_FECHA_CREACION_DT] [datetime]
	,[POLI_USUARIO_MODIFICACION_VC] [varchar](20)
	,[POLI_FECHA_MODIFICACION_DT] [datetime]
	,[POLI_ESTADO_BT] [bit]
	,CONSTRAINT [PK_POLITICA] PRIMARY KEY ([POLI_POLITICA_ID_BI])
	);
GO
/****** Object:  Table [weco].[]    Script Date: 26/10/2020 16:06:22 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [weco].[USUARIO_POLITICA] (
	[USPO_USUARIO_POLITICA_ID_BI] [bigint] IDENTITY(1, 1) NOT NULL
	,[USPO_USUA_ID_BI][bigint] NOT NULL
    ,[USPO_POLI_ID_BI] [bigint] NOT NULL
	,[USPO_APP_USUARIO_ID_VC] [varchar](max)
	,[USPO_USUARIO_CREACION_VC] [varchar](20)
	,[USPO_FECHA_CREACION_DT] [datetime]
	,[USPO_USUARIO_MODIFICACION_VC] [varchar](20)
	,[USPO_FECHA_MODIFICACION_DT] [datetime]
	,[USPO_ESTADO_BT] [bit]
	,CONSTRAINT [PK_USUARIO_POLITICA] PRIMARY KEY ([USPO_USUARIO_POLITICA_ID_BI])
	,CONSTRAINT [FK_USUARIO_POLITICA_1] FOREIGN KEY ([USPO_USUA_ID_BI]) REFERENCES [weco].[USUARIO_WEP_API] ([USWA_USUARIO_WEP_API_ID_BI]) 
	,CONSTRAINT [FK_USUARIO_POLITICA_2] FOREIGN KEY ([USPO_POLI_ID_BI]) REFERENCES [weco].[POLITICA] ([POLI_POLITICA_ID_BI]) 
	);
CREATE INDEX INDEX_USUARIO_POLITICA_1 ON [weco].[USUARIO_POLITICA]([USPO_USUA_ID_BI]);
CREATE INDEX INDEX_USUARIO_POLITICA_2 ON [weco].[USUARIO_POLITICA]([USPO_POLI_ID_BI]);
GO

/****** Object:  Table [weco].[HISTORIAL_CONSUMO_API_ECOFUTURO]    Script Date: 26/10/2020 16:06:22 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [weco].[HISTORIAL_CONSUMO_API_ECOFUTURO] (
	[HIAE_ID_BI] [bigint] IDENTITY(1, 1) NOT NULL
	,[HIAE_WEAP_NOMBRE_VC][varchar] (300)
    ,[HIAE_HOST_VC] [varchar](50) 
	,[HIAE_ID_CORRELACION_VC] [varchar](200)
	,[HIAE_APP_USUARIO_ID_VC] [varchar](20)
	,[HIAE_SOLICITUD_VC] [varchar](max)
	,[HIAE_FECHA_SOLICITUD_DT] [datetime]
	,[HIAE_RESPUESTA_VC] [varchar](max)
	,[HIAE_FECHA_RESPUESTA_DT] [datetime]
	,[HIAE_CODIGO_RESPUESTA_VC] [varchar](3)
	,[HIAE_ESTADO_BT] [bit]
	,CONSTRAINT [PK_HISTORIAL_CONSUMO] PRIMARY KEY ([HIAE_ID_BI])
	);
GO

/****** Object:  Table [weco].[TOKEN_ACTUALIZACION]    Script Date: 26/10/2020 16:06:22 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
CREATE TABLE [weco].[TOKEN_ACTUALIZACION] (
	[TOAC_TOKEN_ACTUALIZACION_ID_BI] [bigint] IDENTITY(1, 1) NOT NULL
	,[TOAC_CLIENTE_ID_BI][bigint]
    ,[TOAC_TOKEN_VC] [varchar](max) 
	,[TOAC_FECHA_EXPIRACION_TOKEN_DT] [datetime]
	,[TOAC_ESTADO_EXPIRACION_BT] [bit]
	,[TOAC_IP_CREACION_TOKEN_VC] [varchar](20)
	,[TOAC_FECHA_REVOCACION_TOKEN_DT] [datetime]
	,[TOAC_IP_REVOCACION_TOKEN_VC] [varchar](20)
	,[TOAC_TOKEN_REEMPLAZADO_TOKEN_VC] [varchar](max)
	,[TOAC_ACTIVE_TOKEN_BT] [bit]
	,[TOAC_USUARIO_CREACION_VC] [varchar](20)
	,[TOAC_FECHA_CREACION_DT] [datetime]
	,[TOAC_USUARIO_MODIFICACION_VC] [varchar](20)
	,[TOAC_FECHA_MODIFICACION_DT] [datetime]
	,[TOAC_ESTADO_BT] [bit]
	,CONSTRAINT [PK_TOKEN_ACTUALIZACION] PRIMARY KEY ([TOAC_TOKEN_ACTUALIZACION_ID_BI])
	,CONSTRAINT [FK_CLIENTE_TOKEN_ACTUALIZACION] FOREIGN KEY ([TOAC_CLIENTE_ID_BI]) REFERENCES [weco].[CLIENTE] ([CLIE_CLIENTE_ID_BI]) 
	);
	CREATE INDEX INDEX_CLIENTE_TOKEN_ACTUALIZACION ON [weco].[TOKEN_ACTUALIZACION]([TOAC_CLIENTE_ID_BI]);

GO