CREATE DATABASE [BD_API_ECOFUTURO] ON PRIMARY (
	NAME = N'BD_API_ECOFUTURO_data'
	,FILENAME = N'E:\SQLData\BD_API_ECOFUTURO_data.mdf'
	,SIZE = 3072 KB
	,MAXSIZE = UNLIMITED
	,FILEGROWTH = 1024 KB
	) LOG ON (
	NAME = N'BD_API_ECOFUTURO_log'
	,FILENAME = N'E:\SQLLog\BD_API_ECOFUTURO_log.ldf'
	,SIZE = 1024 KB
	,MAXSIZE = 2048 GB
	,FILEGROWTH = 10 %
	) 
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_API_ECOFUTURO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_API_ECOFUTURO] SET ANSI_NULL_DEFAULT OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET ANSI_NULLS OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET ANSI_PADDING OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET ANSI_WARNINGS OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET ARITHABORT OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET AUTO_CLOSE OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET AUTO_SHRINK OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET AUTO_UPDATE_STATISTICS ON 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET CURSOR_DEFAULT  GLOBAL 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET NUMERIC_ROUNDABORT OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET QUOTED_IDENTIFIER OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET RECURSIVE_TRIGGERS OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET  DISABLE_BROKER 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET TRUSTWORTHY OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET PARAMETERIZATION SIMPLE 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET READ_COMMITTED_SNAPSHOT OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET HONOR_BROKER_PRIORITY OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET RECOVERY SIMPLE 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET  MULTI_USER 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET PAGE_VERIFY CHECKSUM  
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET DB_CHAINING OFF 
GO				
				
ALTER DATABASE [BD_API_ECOFUTURO] SET  READ_WRITE 
GO

