USE BD_API_ECOFUTURO
GO

GRANT DELETE ON OBJECT::	[weco].CLIENTE	TO [UsrBD_API_ECOFUTURO];
GRANT INSERT ON OBJECT::	[weco].CLIENTE	TO [UsrBD_API_ECOFUTURO];
GRANT SELECT ON OBJECT::	[weco].CLIENTE	TO [UsrBD_API_ECOFUTURO];
GRANT UPDATE ON OBJECT::	[weco].CLIENTE	TO [UsrBD_API_ECOFUTURO];

GRANT DELETE ON OBJECT::	[weco].HISTORIAL_CONSUMO_API_ECOFUTURO	TO [UsrBD_API_ECOFUTURO];
GRANT INSERT ON OBJECT::	[weco].HISTORIAL_CONSUMO_API_ECOFUTURO	TO [UsrBD_API_ECOFUTURO];
GRANT SELECT ON OBJECT::	[weco].HISTORIAL_CONSUMO_API_ECOFUTURO	TO [UsrBD_API_ECOFUTURO];
GRANT UPDATE ON OBJECT::	[weco].HISTORIAL_CONSUMO_API_ECOFUTURO	TO [UsrBD_API_ECOFUTURO];

GRANT DELETE ON OBJECT::	[weco].MODULO	TO [UsrBD_API_ECOFUTURO];
GRANT INSERT ON OBJECT::	[weco].MODULO	TO [UsrBD_API_ECOFUTURO];
GRANT SELECT ON OBJECT::	[weco].MODULO	TO [UsrBD_API_ECOFUTURO];
GRANT UPDATE ON OBJECT::	[weco].MODULO	TO [UsrBD_API_ECOFUTURO];

GRANT DELETE ON OBJECT::	[weco].POLITICA	TO [UsrBD_API_ECOFUTURO];
GRANT INSERT ON OBJECT::	[weco].POLITICA	TO [UsrBD_API_ECOFUTURO];
GRANT SELECT ON OBJECT::	[weco].POLITICA	TO [UsrBD_API_ECOFUTURO];
GRANT UPDATE ON OBJECT::	[weco].POLITICA	TO [UsrBD_API_ECOFUTURO];

GRANT DELETE ON OBJECT::	[weco].PREGUNTA	TO [UsrBD_API_ECOFUTURO];
GRANT INSERT ON OBJECT::	[weco].PREGUNTA	TO [UsrBD_API_ECOFUTURO];
GRANT SELECT ON OBJECT::	[weco].PREGUNTA	TO [UsrBD_API_ECOFUTURO];
GRANT UPDATE ON OBJECT::	[weco].PREGUNTA	TO [UsrBD_API_ECOFUTURO];

GRANT DELETE ON OBJECT::	[weco].RESPUESTA	TO [UsrBD_API_ECOFUTURO];
GRANT INSERT ON OBJECT::	[weco].RESPUESTA	TO [UsrBD_API_ECOFUTURO];
GRANT SELECT ON OBJECT::	[weco].RESPUESTA	TO [UsrBD_API_ECOFUTURO];
GRANT UPDATE ON OBJECT::	[weco].RESPUESTA	TO [UsrBD_API_ECOFUTURO];

GRANT DELETE ON OBJECT::	[weco].RESPUESTA_CLIENTE	TO [UsrBD_API_ECOFUTURO];
GRANT INSERT ON OBJECT::	[weco].RESPUESTA_CLIENTE	TO [UsrBD_API_ECOFUTURO];
GRANT SELECT ON OBJECT::	[weco].RESPUESTA_CLIENTE	TO [UsrBD_API_ECOFUTURO];
GRANT UPDATE ON OBJECT::	[weco].RESPUESTA_CLIENTE	TO [UsrBD_API_ECOFUTURO];

GRANT DELETE ON OBJECT::	[weco].USUARIO_POLITICA	TO [UsrBD_API_ECOFUTURO];
GRANT INSERT ON OBJECT::	[weco].USUARIO_POLITICA	TO [UsrBD_API_ECOFUTURO];
GRANT SELECT ON OBJECT::	[weco].USUARIO_POLITICA	TO [UsrBD_API_ECOFUTURO];
GRANT UPDATE ON OBJECT::	[weco].USUARIO_POLITICA	TO [UsrBD_API_ECOFUTURO];

GRANT DELETE ON OBJECT::	[weco].USUARIO_WEP_API	TO [UsrBD_API_ECOFUTURO];
GRANT INSERT ON OBJECT::	[weco].USUARIO_WEP_API	TO [UsrBD_API_ECOFUTURO];
GRANT SELECT ON OBJECT::	[weco].USUARIO_WEP_API	TO [UsrBD_API_ECOFUTURO];
GRANT UPDATE ON OBJECT::	[weco].USUARIO_WEP_API	TO [UsrBD_API_ECOFUTURO];


GRANT EXECUTE ON OBJECT::	[weco].CLIENTE_InsertIfNotexist	TO [UsrBD_API_ECOFUTURO]; 
GRANT EXECUTE ON OBJECT::	[weco].USUARIO_Authenticate	TO [UsrBD_API_ECOFUTURO];
GRANT EXECUTE ON OBJECT::	[weco].USUARIO_POLITICA_Authorize	TO [UsrBD_API_ECOFUTURO];
GRANT EXECUTE ON OBJECT::	[weco].HISTORIAL_CONSUMO_API_ECOFUTURO_Insert	TO [UsrBD_API_ECOFUTURO];